#!/bin/bash

set -euo pipefail

if [[ ! -d .git ]]; then
    git init --initial-branch="${DRONE_REPO_BRANCH}"
    git remote add origin "${DRONE_REMOTE_URL}"
fi

# the branch may be empty for certain event types,
# such as github deployment events. If the branch
# is empty we checkout the sha directly. Note that
# we intentionally omit the depth flag to avoid
# failed clones due to lack of history.
if [[ -z "${DRONE_COMMIT_BRANCH:-}" ]]; then
    set -x
    git fetch origin
    git checkout -qf "${DRONE_COMMIT_SHA}"
    exit 0
fi

# the commit sha may be empty for builds that are
# manually triggered in Harness CI Enterprise. If
# the commit is empty we clone the branch.
if [[ -z "${DRONE_COMMIT_SHA:-}" ]]; then
    checkout_ref="origin/${DRONE_COMMIT_BRANCH}"
else
    checkout_ref="${DRONE_COMMIT_SHA}"
fi

set -euo pipefail
set -x

git fetch ${PLUGIN_DEPTH:+"--depth=${PLUGIN_DEPTH}"} origin "+refs/heads/${DRONE_REPO_BRANCH}:"
git fetch ${PLUGIN_DEPTH:+"--depth=${PLUGIN_DEPTH}"} origin "+refs/heads/${DRONE_COMMIT_BRANCH}:"
git checkout -b "${DRONE_COMMIT_BRANCH}" "${checkout_ref}"
