#!/bin/bash

if [[ ! -d .git ]]; then
    git init
    git remote add origin "${DRONE_REMOTE_URL}"
fi

set -e
set -x

git fetch ${PLUGIN_DEPTH:+"--depth=${PLUGIN_DEPTH}"} origin "+refs/tags/${DRONE_TAG}:"
git checkout -qf FETCH_HEAD
