name: "Build and Publish"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/workflows/ci.yaml"
  schedule:
    # Always run at least once a month to regularly rebuild the
    # image with the latest packages. Run one week after the
    # tests are scheduled to run, so that there's time to fix
    # any problems.
    - cron: "0 0 8 * *"
  workflow_dispatch:

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "${{ github.repository }}"

jobs:
  main:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64,linux/arm/v7"

      - name: "Set up Buildkit"
        id: "buildx-setup"
        uses: docker/setup-buildx-action@v2

      - name: "Log in to the container registery"
        uses: docker/login-action@v2
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Get date for image tag"
        id: "get-date"
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: "bash"

      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.get-date.outputs.date }}

      - name: "Build and push container image"
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64,linux/arm64,linux/arm/v7"
