name: "CI"

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  schedule:
    # Always run at least once a month to regularly run the tests with
    # recent versions of git and pytest.
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: "ubuntu-latest"

    env:
      PYTHON_VERSION: "3.10"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Install and configure Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

      # Guarantee we don't go more than a month without updating to the
      # latest version of pytest.
      - name: "Get month-based date for cache key"
        id: "get-date"
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m")"
        shell: "bash"

      - name: "Cache pip cache"
        uses: "actions/cache@v4"
        with:
          path: "~/.cache/pip"
          key: "${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ steps.get-date.outputs.date }}"

      - name: "Install pytest"
        run: "pip install pytest"

      - name: "Run tests"
        run: "pytest"

      - name: "Run Shellcheck"
        uses: "ludeeus/action-shellcheck@master"
        with:
          scandir: "./scripts"

      - name: "Run Hadolint"
        uses: "hadolint/hadolint-action@v3.1.0"
